import pandas as pd
df = pd.read_csv("day06_user_data.csv")
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['income'] = pd.to_numeric(df['income'], errors='coerce')
age_mean = df['age'].mean()
age_median = df['age'].median()
age_mode = df['age'].mode()
income_mean = df['income'].mean()
income_median = df['income'].median()
income_mode = df['income'].mode()
print(age_mean)
print(age_median)
print(age_mode.tolist())
print(income_mean)
print(income_median)
print(income_mode.tolist())
